yasserg/crawler4j

- README.md
`getOutgoingUrls()` returns a `Set` of `WebURL`s. The Quickstart example was incorrectly using a `List` of `WebURL`s.
> Update README to use Set for getOutgoingUrls()

- src/main/java/edu/uci/ics/crawler4j/crawler/CrawlConfig.java
- src/main/java/edu/uci/ics/crawler4j/fetcher/PageFetcher.java
Hi,
I have had a requirement to crawl a number of content-managed sites running on the same local server instance and needed to pass a host header for the page fetcher to use. The HttpClientBuilder class can handle this using default headers - but there was nowhere to configure this in the CrawlConfig.
This change is backward compatible - but provides the ability to configure headers in page fetches.
Hoping you can include this in the project.
Alun
> Added default request header configuration.

- src/main/java/edu/uci/ics/crawler4j/url/TLDList.java
The absolute path /tld-name.txt in the TLDList change that I recently submitted made the test fail when no JAR was being used. This patch should fix that.
> Fix tldlist absolute path

- src/main/java/edu/uci/ics/crawler4j/fetcher/PageFetcher.java
This should fix the freezing of the crawler in case of too many to big files described in issue #52 or #72.
> Fix for issue #52 - Close entity when page is to big

- src/main/java/edu/uci/ics/crawler4j/crawler/WebCrawler.java
- src/main/java/edu/uci/ics/crawler4j/fetcher/PageFetcher.java
While 200 is the most common HTTP status for a succesful request, it's not the only one: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#2xx_Success
There's at least 202, 203 and 206 may contain proper content, where the HTTP Status Code is giving additional meta-information about the nature of the content, and ALL 2XX-codes indicate a succesful request.
Currently, the page fetcher treats all non-200, non-3xx pages as some kind of error and does not parse the content, while all 2XX codes indicate success.
This patch therefore changes this to accept all 2XX status codes as a succesful request.
> Accept and parse 2xx status codes, instead of just 200

- src/main/java/edu/uci/ics/crawler4j/crawler/CrawlConfig.java
- src/main/java/edu/uci/ics/crawler4j/crawler/CrawlController.java
Note: I recently discovered that you moved from google code to Github. I've been using and modifying crawlerj4 for a while now and now I'm able to submit pull requests to allow you to merge them. I rebased all my (relevant) patches on the new master, so they should be easy to merge. I hope you consider some or all of them useful.
Description of this patch:
Add a setting to configure the behavior of the crawler when the queue is empty. When set to true, it will shut down. When set to false, it will keep running. This can be useful when building a daemon, waiting for more work.
> Allow crawler to keep running with an empty queue

- src/main/java/edu/uci/ics/crawler4j/parser/HtmlContentHandler.java
Note: I recently discovered that you moved from google code to Github. I've been using and modifying crawlerj4 for a while now and now I'm able to submit pull requests to allow you to merge them. I rebased all my (relevant) patches on the new master, so they should be easy to merge. I hope you consider some or all of them useful.
Description of this patch:
Copy/paste problem probably. Also fixed a bug where meta http-equiv=refresh was incorrectly parsed:
when no URL was specified a NULL URL would be added.
> Fix bug where metaRefresh was used instead of metaLocation

- src/main/java/edu/uci/ics/crawler4j/crawler/CrawlConfig.java
- src/main/java/edu/uci/ics/crawler4j/parser/Parser.java
Note: I recently discovered that you moved from google code to Github. I've been using and modifying crawlerj4 for a while now and now I'm able to submit pull requests to allow you to merge them. I rebased all my (relevant) patches on the new master, so they should be easy to merge. I hope you consider some or all of them useful.
Description of this patch:
Added configuration parameter processBinaryContentInCrawling determines if binary content must be processed by TIKA in addition to being retrieved at all (which is controlled by includeBinaryContentInCrawling). This is useful if you want to be able to retrieve the binary content but do not care if links inside are processed. This can improve the performance when handling binary
documents strongly.
> Added configuration parameter processBinaryContentInCrawling

- src/main/java/edu/uci/ics/crawler4j/crawler/WebCrawler.java
Added a new onUnhandledException method to WebCrawler, that allows a subclass to detect what type of exception occured and to handle it if desired.
To give an example: I'm using this to detect UnknownHostException and SocketTimeoutException which need to be handled separately: remove the URL from the queue or reschedule the URL after a day or so.
> Add onUnhandledException callback to handle unhandled exceptions during fetching

- src/main/java/edu/uci/ics/crawler4j/url/URLCanonicalizer.java
- src/test/java/edu/uci/ics/crawler4j/tests/URLCanonicalizerTest.java
The parameters do not retain their original ordering in the URLs. The URLCanonicalizer references wikipedia, which states that the lexicographical ordering of parameters can cause problems (it has for me), yet the canonicalizer still lexicographically orders the parameters.
I have changed all instances of SortedMap during the url parameter conocalization process with a LinkedHashMap, which retains the ordering of the map Entrys based on the ordering of their insertion in the map.
I can not think of any disadvantages of retaining the original ordering of the url parameters.
> The canonicalization of request URLs alphabetizes the parameters

- src/main/java/edu/uci/ics/crawler4j/crawler/WebCrawler.java
When shutting down the Crawl Controller explicitly, sometimes the Berkeley DB environment is closed before the call to store the currently processed page URL. This causes an exception to be thrown by the BDB Environment:
```
java.lang.IllegalStateException: Attempt to use non-open Environment object().
at com.sleepycat.je.Environment.checkHandleIsValid(Environment.java:2153) ~[je-5.0.73.jar:5.0.73]
at com.sleepycat.je.Environment.beginTransactionInternal(Environment.java:1312) ~[je-5.0.73.jar:5.0.73]
at com.sleepycat.je.Environment.beginTransaction(Environment.java:1284) ~[je-5.0.73.jar:5.0.73]
at edu.uci.ics.crawler4j.frontier.InProcessPagesDB.removeURL(InProcessPagesDB.java:58) ~[crawler4j-4.1.jar:na]
at edu.uci.ics.crawler4j.frontier.Frontier.setProcessed(Frontier.java:163) …
```
> Attempt to use already closed Environment object when shutting down crawl controller explicitly

- src/main/java/edu/uci/ics/crawler4j/robotstxt/RobotstxtParser.java
- src/test/java/edu/uci/ics/crawler4j/tests/RobotstxtParserNonLowercaseUserAgentTest.java
In RobotstxtParser, the robots.txt directives user agent is converted to lowercase. Then the parser checks to see if that lowercase user agent string contains the crawler's user agent. If the crawler's user agent has any non-lowercase characters, then this check will always return false.
An easy fix is to lowercase the crawler's user agent, which I have done. The other option was to remove the conversion to lowercase of the robots.txt user agent, but I thought the first option was more inline with the inferred intent of the class.
A unit test is included.
> When checking robots.txt directive user agent against crawler user agent use lowercase.

- src/main/java/edu/uci/ics/crawler4j/crawler/WebCrawler.java
- src/main/java/edu/uci/ics/crawler4j/robotstxt/RobotstxtServer.java
This pull-request prevents a few errors that occur if a server fails to provide a Content-Type header.
> dont throw NPE if Content-Type is missing

- src/main/java/edu/uci/ics/crawler4j/fetcher/PageFetcher.java
I occurred the error:
> WARN  2016-04-13/17:00:26.428 [Crawler 1] WebCrawler -|79581|- Unhandled exception while fetching http://mp.weixin.qq.com/s?__biz=MzIzNzA0ODQxOA%3D%3D&mid=401543508&idx=1&sn=292e96fd82ca1207de11af1aacd03353: null
> INFO  2016-04-13/17:00:26.429 [Crawler 1] WebCrawler -|79581|- Stacktrace: 
> org.apache.http.client.ClientProtocolException
> 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
> 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
> 	at edu.uci.ics.crawler4j.fetcher.PageFetcher.fetchPage(PageFetcher.java:274)
> 	at edu.uci.ics.crawler4j.crawler.WebCrawler.processPage(WebCrawler.java:323) …
> Fixed  HttpException: Unsupported cookie policy [DEFAULT]

- src/main/java/edu/uci/ics/crawler4j/frontier/Frontier.java
This allows a consumer to roughly determine progress by comparing processed pages vs scheduled pages.
> Update frontier - add method to grab number of scheduled pages

- pom.xml
Java 1.8 is required to compile this project. Prior to this update I was getting:
```
java.lang.UnsupportedClassVersionError: com/puppycrawl/tools/checkstyle/api/AuditListener : Unsupported major.minor version 52.0
```
CheckStyle 7.x requires Java 8.
> Update compile version to 1.8

- src/main/java/edu/uci/ics/crawler4j/crawler/WebCrawler.java
- src/main/java/edu/uci/ics/crawler4j/parser/AllTagMapper.java
- src/main/java/edu/uci/ics/crawler4j/parser/HtmlContentHandler.java
- src/main/java/edu/uci/ics/crawler4j/parser/Parser.java
- src/test/java/edu/uci/ics/crawler4j/examples/localdata/Downloader.java
- src/test/java/edu/uci/ics/crawler4j/tests/HtmlContentHandlerTest.java
This PR includes some changes from https://github.com/yasserg/crawler4j/pull/114 to update the crawler to parse script elements and treat them like links (follow the src if it exists).
> Parse script elements as links

- pom.xml
updates slf4j to 1.7.22 (was 1.7.21)
updates guava to 21.0 (was 19.0)
updates apache http to 4.5.3 (was 4.5.2)
updates berkley db to 5.0.84 (was 5.0.73)
updates jacoco to 0.7.9 (was 0.7.7.201606060606)
> Updates Third Party Dependencies

- src/main/java/edu/uci/ics/crawler4j/crawler/CrawlConfig.java
- src/main/java/edu/uci/ics/crawler4j/crawler/WebCrawler.java
- src/main/java/edu/uci/ics/crawler4j/parser/ExtractedUrlAnchorPair.java
- src/main/java/edu/uci/ics/crawler4j/parser/HtmlContentHandler.java
- src/main/java/edu/uci/ics/crawler4j/parser/HtmlParseData.java
- src/main/java/edu/uci/ics/crawler4j/parser/Parser.java
- src/main/java/edu/uci/ics/crawler4j/url/WebURL.java
- src/test/groovy/edu/uci/ics/crawler4j/crawler/NoFollowTest.groovy
- src/test/groovy/edu/uci/ics/crawler4j/crawler/NoIndexTest.groovy
- src/test/java/edu/uci/ics/crawler4j/tests/HtmlContentHandlerTest.java
Pages with a meta robots "noindex" are *not* passed to WebCrawler.visit(). "a" links with a "rel=nofollow" or links on pages with a meta robots "nofollow" are ignored. These settings are configurable of course.
> Add processing of meta robots flags and rel="nofollow"

- README.md
It looks like the code all got moved from `src/` to `crawler4j/src` so these
links turned into 404s. Also updated all the links to relative paths so
they work properly in branches and forks.
See: https://help.github.com/articles/about-readmes/#relative-links-and-image-paths-in-readme-files
> Fix readme example links

- crawler4j/src/test/groovy/edu/uci/ics/crawler4j/config/CustomDnsResolverTest.groovy
- crawler4j/src/test/groovy/edu/uci/ics/crawler4j/crawler/CrawlerWithJSTest.groovy
- crawler4j/src/test/groovy/edu/uci/ics/crawler4j/crawler/NoFollowTest.groovy
- crawler4j/src/test/groovy/edu/uci/ics/crawler4j/crawler/NoIndexTest.groovy
- crawler4j/src/test/groovy/edu/uci/ics/crawler4j/crawler/RedirectHandlerTest.groovy
- crawler4j/src/test/groovy/edu/uci/ics/crawler4j/crawler/TimeoutTest.groovy
- crawler4j/src/test/groovy/edu/uci/ics/crawler4j/crawler/WebCrawlerTest.groovy
- crawler4j/src/test/java/edu/uci/ics/crawler4j/tests/fetcher/PageFetcherHtmlTest.java
When default WireMock port (8080) is already in use, it's hard to run unit tests. This change configures WireMock to use dynamic port allocation
> Use dynamic port for WireMock in unit tests

- README.md
I found a wrong link in README.
(This was introduced in https://github.com/yasserg/crawler4j/commit/349a42d11b902b2ea3b28544f3b11abf8cc610c6)
> Fix a link in README

- crawler4j/src/main/java/edu/uci/ics/crawler4j/crawler/CrawlConfig.java
- crawler4j/src/main/java/edu/uci/ics/crawler4j/crawler/CrawlController.java
- crawler4j/src/main/java/edu/uci/ics/crawler4j/crawler/WebCrawler.java
- crawler4j/src/main/java/edu/uci/ics/crawler4j/parser/HtmlParseData.java
- crawler4j/src/main/java/edu/uci/ics/crawler4j/parser/HtmlParser.java
- crawler4j/src/main/java/edu/uci/ics/crawler4j/parser/Parser.java
- crawler4j/src/main/java/edu/uci/ics/crawler4j/parser/TikaHtmlParser.java
I have a concrete use case where I need to implement my own logic to extract outgoing urls from html pages.
This could be achieved quite simply allowing to inject a custom parser from CrawlController, in a similar way as the custom PageFetcher. Since the default parser has three behaviour (binary, text and html) I encapsulated the html parsing code in a separate class (TikaHtmlParser) which can be replaced if needed.
I created a pull request which is backward-compatible with the existing codebase. In my opinion it brings also cleaner code. All existing test passes. Now also the stylecheck should pass.
We can discuss it if needed.
> Internal parser customization (fixed)

- crawler4j/src/main/java/edu/uci/ics/crawler4j/url/TLDList.java
If the database is empty or "setResumableCrawling==false" java will report an error below:
Exception in thread "main" java.lang.NullPointerException
at java.io.Reader.(Unknown Source)
at java.io.InputStreamReader.(Unknown Source)
at edu.uci.ics.crawler4j.url.TLDList.readStream(TLDList.java:51)
at edu.uci.ics.crawler4j.url.TLDList.loadFromFiles(TLDList.java:119)
at edu.uci.ics.crawler4j.url.TLDList.tldSupplier(TLDList.java:98)
at edu.uci.ics.crawler4j.url.TLDList.lambda$1(TLDList.java:130)
at java.util.HashMap.computeIfAbsent(Unknown Source)
at edu.uci.ics.crawler4j.url.TLDList.lambda$0(TLDList.java:130)
at edu.uci.ics.crawler4j.url.TLDList.contains(TLDList.java:80)
at edu.uci.ics.crawler4j.url.WebURL.setURL(WebURL.java:81)
at edu.uci.ics.crawler4j.crawler.CrawlController.addSeed(CrawlContr …
> Fix issues of NullPointerException when frontier/ is empty

- LICENSE
http://www.apache.org/dev/apply-license.html#new
An added benefit is that Github should automatically recognize the license.  Currently for crawler4j, GitHub is not recognizing the license.  When you look in your repositories list it shows "NOASSERTION" for license:
> Update ASF 2.0 license per Apache current guidelines

- crawler4j-examples/crawler4j-examples-postgres/README.md
- crawler4j-examples/crawler4j-examples-postgres/pom.xml
- pom.xml
Allow docker exe files to be specified in local maven config files.  Otherwise Windows users need to specify the exe locations as environment variables.
> make the postgres tests easier to run on Windows

- crawler4j-examples/crawler4j-examples-base/pom.xml
- crawler4j/pom.xml
- crawler4j/pom.xml.orig
- crawler4j/src/main/java/edu/uci/ics/crawler4j/crawler/CrawlConfig.java
- crawler4j/src/main/java/edu/uci/ics/crawler4j/crawler/CrawlController.java
- crawler4j/src/main/java/edu/uci/ics/crawler4j/crawler/WebCrawler.java
- crawler4j/src/main/java/edu/uci/ics/crawler4j/parser/Parser.java
- crawler4j/src/main/java/edu/uci/ics/crawler4j/parser/TikaHtmlParser.java
- crawler4j/src/main/java/edu/uci/ics/crawler4j/url/TLDList.java
- crawler4j/src/main/java/edu/uci/ics/crawler4j/url/WebURL.java
- crawler4j/src/main/java/edu/uci/ics/crawler4j/util/Net.java
- crawler4j/src/test/groovy/edu/uci/ics/crawler4j/url/PublicSuffixTest.groovy
- crawler4j/src/test/groovy/edu/uci/ics/crawler4j/url/TLDListOnlineTest.groovy
- crawler4j/src/test/resources/public_suffix_list.dat
TLDList is no longer a singleton that can break unit testing after being locked into a single configuration.
Use third party libraries for internal (Guava) and external (https://github.com/whois-server-list/public-suffix-list) public suffix list lookup.
Resolves https://github.com/yasserg/crawler4j/issues/318.
> TLDList updates -- non-singleton, and use third party public suffix list libraries

- crawler4j-examples/crawler4j-examples-base/src/main/resources/logback.xml
- crawler4j/pom.xml
- crawler4j/src/test/resources/logback.xml
- pom.xml
* tighten up logging dependencies to use only SLF4J/Logback, and banning Commons Logging & Log4j
* End-users who use Crawler4j as a dependency can, of course, still switch to a logging implementation of their own choosing
* remove verbose http client messages from the console by default, and log to a file (rewrite every time unit tests are run)
* formatting (indenting) should look better if PR #358 is approved first
> Logging configuration and dependencies

- .travis.yml
More details: https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766
> Switch Travis builds from oraclejdk8 to openjdk8
