.gitignore
src/main/java/edu/uci/ics/crawler4j/crawler/authentication/AuthInfo.java
src/main/java/edu/uci/ics/crawler4j/crawler/authentication/NtAuthInfo.java
src/main/java/edu/uci/ics/crawler4j/fetcher/PageFetcher.java

This adds support for NT authentication to support crawling sites protected by AD.

support for NT authentication

---

src/main/java/edu/uci/ics/crawler4j/crawler/CrawlConfig.java
src/main/java/edu/uci/ics/crawler4j/frontier/Frontier.java

make the magic number 100 to be a final variable.

make the magic number 100 to be a final variable.

---

README.md
src/main/java/edu/uci/ics/crawler4j/crawler/CrawlConfig.java

This will point users and server owners to the right location

Change user agent to reflect new hosting location

---

src/main/java/edu/uci/ics/crawler4j/crawler/CrawlController.java

Hi,
I faced with strict limitation of the current implementation CrawlController. I am not able to start crawling by specifying an inner class as implementation of WebCrawler because you instantiate it using java reflection approach. I suggest adding ability to specify WebCrawlerFactory to leave the way how it is created open for the client of the framework. Also it should allow to integrate your framework with Spring Framework (WebCrawler implementation could be a prototype/singleton bean).
Thank you.

Added a factory for instantiation of WebCrawler in CrawlController

---

src/main/java/edu/uci/ics/crawler4j/crawler/CrawlConfig.java
src/main/java/edu/uci/ics/crawler4j/crawler/CrawlController.java

Including: thread monitoring delay, thread shutdown delay, cleanup delay

Make the various shutdown delays configurable

---

.gitignore
pom.xml

- updates pom.xml to be easier readable by externalizing versions to properties
- adds .gitignore entries for IntelliJ / Eclipse / Maven

Updates .gitignore for Maven / IntelliJ & Pom Readability Improvements

---

src/main/java/edu/uci/ics/crawler4j/crawler/WebCrawler.java

Add support for customizing handling of 3xx pages.

Create handler for 3xx pages

---

pom.xml

Hope this fixes various issues as described in #102

Update Apache Http Components

---

src/main/java/edu/uci/ics/crawler4j/crawler/Page.java

When reading the HttpEntity from the server in the cases when the server did not
respond with Content-Length, the read buffer was automatically allocated to the
size of maxBytes. The value of maxBytes is arbitrary and it usually is set to a
higher value (when setting it, we expect most of the content that we're interested in
to be less than the maximal download size), so for a lot of pages we end up
allocating more memory than needed.
While most of the time this does not cause problems (when the maxDownloadSize is
a couple of MiB or even tens of MiB), when setting it to a higher value (in the
hundreds of MiB) we end up wasting a lot of memory per crawling thread.
In the cases when the download size is very high, it may even cause an out of
memory error (java.lang.OutOfMemoryError: Java …

Better memory management when reading the data from server and enforcing maxBytes

---

README.md

Hi,
This is in reference to the Issue #243.
I have added the changes needed in build.gradle file to include crawler4j as a dependency using gradle build management system.
Thanks,
Harshita

Added installation instructions with gradle

---

README.md

Hello, 
This is to fix the broken link mentioned in the PR #244.

Fixed broken sleepycat url

---

README.md

As per the discussion in #249 added a PR that fixes the issue.

Added binary content crawling config in readme

---

crawler4j/src/main/java/edu/uci/ics/crawler4j/crawler/Configurable.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/crawler/CrawlController.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/fetcher/PageFetcher.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/frontier/Counters.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/frontier/DocIDServer.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/frontier/Frontier.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/parser/Parser.java
crawler4j/src/test/java/edu/uci/ics/crawler4j/tests/fetcher/PageFetcherHtmlOnly.java

- no need for core classes to extends Configurable, good old IoC is better
- deprecated Configurable

#145, see details

---

crawler4j/checkstyle.xml
crawler4j/src/main/java/edu/uci/ics/crawler4j/crawler/CrawlConfig.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/crawler/CrawlController.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/crawler/WebCrawler.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/crawler/authentication/AuthInfo.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/fetcher/PageFetcher.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/parser/Parser.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/parser/TikaHtmlParser.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/url/TLDList.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/url/WebURL.java
crawler4j/src/test/java/edu/uci/ics/crawler4j/tests/fetcher/PageFetcherHtmlOnly.java
crawler4j/src/test/java/edu/uci/ics/crawler4j/tests/fetcher/PageFetcherHtmlTest.java
pom.xml

This makes life easier when working in Eclipse as that's the current Checkstyle version in use.

Update Checkstyle to v8.12

---

README.md

Make the Maven Central badge in readme.md actually link to Maven Central repo

update Maven badge link

---

README.md
crawler4j-examples/crawler4j-examples-base/src/test/java/edu/uci/ics/crawler4j/examples/basic/BasicCrawlController.java
crawler4j-examples/crawler4j-examples-base/src/test/java/edu/uci/ics/crawler4j/examples/basic/BasicCrawler.java
crawler4j-examples/crawler4j-examples-base/src/test/java/edu/uci/ics/crawler4j/examples/localdata/LocalDataCollectorController.java
crawler4j-examples/crawler4j-examples-base/src/test/java/edu/uci/ics/crawler4j/examples/localdata/LocalDataCollectorCrawler.java
crawler4j-examples/crawler4j-examples-base/src/test/java/edu/uci/ics/crawler4j/examples/multiple/MultipleCrawlerController.java
crawler4j-examples/crawler4j-examples-base/src/test/java/edu/uci/ics/crawler4j/examples/shutdown/BasicCrawler.java
crawler4j-examples/crawler4j-examples-base/src/test/java/edu/uci/ics/crawler4j/examples/shutdown/ControllerWithShutdown.java
crawler4j-examples/crawler4j-examples-base/src/test/java/edu/uci/ics/crawler4j/examples/statushandler/StatusHandlerCrawlController.java
crawler4j-examples/crawler4j-examples-base/src/test/java/edu/uci/ics/crawler4j/examples/statushandler/StatusHandlerCrawler.java

Pretty much everything these days just redirects http -> https, so this works out better for testing.

Update example URLs to use https instead of http

---

crawler4j/src/main/java/edu/uci/ics/crawler4j/crawler/CrawlConfig.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/crawler/WebCrawler.java

Allow changing the default batch read window size from 50 to some other value

make the batch read transaction size configurable

---

.gitignore
crawler4j-examples/crawler4j-examples-base/.gitignore

ignore local Maven config files that should never be checked in

ignore local Maven config

---

.editorconfig

specify some basic formatting rules for all editors to follow

use editor config (https://EditorConfig.org)

---

crawler4j-examples/crawler4j-examples-base/pom.xml
crawler4j/pom.xml
crawler4j/pom.xml.orig
crawler4j/src/main/java/edu/uci/ics/crawler4j/crawler/CrawlConfig.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/crawler/CrawlController.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/crawler/WebCrawler.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/parser/Parser.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/parser/TikaHtmlParser.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/url/TLDList.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/url/WebURL.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/util/Net.java
crawler4j/src/test/groovy/edu/uci/ics/crawler4j/parser/HtmlParserTest.groovy
crawler4j/src/test/groovy/edu/uci/ics/crawler4j/url/PublicSuffixTest.groovy
crawler4j/src/test/groovy/edu/uci/ics/crawler4j/url/TLDListOnlineTest.groovy
crawler4j/src/test/resources/html/wiki.c2.com.html
crawler4j/src/test/resources/public_suffix_list.dat

Fix for issue #346.
This depends on PR #367

Detect content type in Tika

---

crawler4j/pom.xml
crawler4j/src/main/java/edu/uci/ics/crawler4j/crawler/CrawlConfig.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/parser/Parser.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/util/Net.java
crawler4j/src/test/groovy/edu/uci/ics/crawler4j/util/NetTest.groovy

Fixes https://github.com/yasserg/crawler4j/issues/348

Fix for issue #348

---

crawler4j/src/main/java/edu/uci/ics/crawler4j/parser/CssParseData.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/parser/Parser.java
crawler4j/src/main/java/edu/uci/ics/crawler4j/util/Util.java
crawler4j/src/test/groovy/edu/uci/ics/crawler4j/parser/CssParseDataTest.groovy
crawler4j/src/test/resources/css/absolute.css
crawler4j/src/test/resources/css/quotes.css
crawler4j/src/test/resources/css/relative.css

Basic support for extracting styles, fonts and imagens inside css files.

Parse css for links matching url(*)in tags @import and @font-face

---

crawler4j/src/main/java/edu/uci/ics/crawler4j/robotstxt/RobotstxtServer.java

As per: https://developers.google.com/search/reference/robots_txt

Update the maximum size of a robots.txt file
